name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  quality-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 app tests

      - name: Format check (black)
        run: black --check .

      - name: Type-check (mypy)
        run: mypy app

      - name: Run tests (pytest)
        run: pytest

  docker-build-and-push:
    needs: quality-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/fraud-service:latest
          docker build -t "$IMAGE" .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/fraud-service:latest
          docker push "$IMAGE"
